---
title: "R Notebook"
output: html_notebook
---

Black-Scholes Formula

```{r}

# calculate Call using Black-Scholes Formula

BlackScholes <- function(S0,K,T,r,sigma)
{
  d1 <- (log(S0/K) + ( r + (sigma ^2)/2) * T)/(sigma*sqrt(T))
  d2 <- d1-sigma*sqrt(T)
  
  return(pnorm(d1)*S0 - pnorm(d2)*K*exp(-r*T))
}

# PutCall parity to find put price

putFromPutCall <- function(Ct, r, T, K, S0)
{
  return(Ct + exp(-r * T) * K - S0)
}

# PutCall parity to find call price

callFromPutCall <- function(P, r, T, K, S0)
{
  return(P - exp(-r * T) * K + S0)
}

Expectation <- function(stdev, mu)
{
  return(exp(mu + stdev/2))
}

IV <- function(p, s0, k, t, r, sigmas=seq(0,0.05,by=0.0001)) #sigmas may need to be changed depending on question
{
    # Calculates implied volatility
    ps <- BlackScholes(s0,k,t,r,sigmas)
    
    sigma <- sigmas[round(ps,2)==p]
    
    p <- ps[round(ps,2)==p]
    
    return(c(sigma=sigma, p=p))
}
```


```{r}
# Implied volatility example from notes.
IV(5.3, 47.16, 42.5, 24, 0.0001947)
```


Implied Volatility (Example from 2020 mid sem)

```{r}

s0 = 47.5; r = 0.02; T = 1/3; K = 50     # set up 
sigmas = seq(0, 1.5, by = 0.0005)        # set up different volatility
p = BlackScholes(s0, K, T, r, sigmas)    
implied = sigmas[ round(p, 2) == 5.21]   # replace 5.21 with market price of question

```

Expectation
```{r}
mu = 0.02
stdev = 0.01
Expectation(stdev,mu)

```


Black-Scholes calculation
```{r}
S0 = 100
K = 90
T = 0.25
r = 0.1
sigma = 0.4

BlackScholes(S0,K,T,r,sigma)

```

Put call parity
```{r}
Ct = BlackScholes(S0,K,T,r,sigma)
putFromPutCall(Ct, r, T, K, S0)
```

